name: Pest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ "8.2", "8.3" ]
        laravel: [ "10", "11" ]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          extensions: mbstring, dom, curl, json
      - run: composer validate
      - if: matrix.laravel == '10'
        run: composer require --no-update orchestra/testbench:^8
      - if: matrix.laravel == '11'
        run: composer require --no-update orchestra/testbench:^9
      - run: composer install --no-interaction --prefer-dist
      - run: vendor/bin/pest --ci
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.php }}-laravel-${{ matrix.laravel }}
          path: coverage.xml
